version: "3.8"

services:
    backend:
        build:
            context: ./server
            dockerfile: Dockerfile
        ports:
            - "8080:8080"
        container_name: tshirt-backend
        restart: unless-stopped
        networks:
            - tshirt-network

    frontend:
        build:
            context: ./client
            dockerfile: Dockerfile
        ports:
            - "5173:5173"
        restart: unless-stopped
        container_name: tshirt-frontend
        depends_on:
            - backend
        networks:
            - tshirt-network

networks:
    tshirt-network:
        driver: bridge
